Repository Step3-kakao-tech-campus/Team13_FE, pull requests merged in 2023-11, with the labels that each got.

#104 fix: CelebrityDetail.page.jsx import문 수정 - 배포용
  Dockerfile
  src/src/pages/CelebrityDetail.page.jsx
Labels: hotfix

#105 배포 관련 쿠버네티스 설정
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/service.yaml
  src/src/components/celebrity-detail/CelebTextInfo.jsx
  src/src/pages/CelebrityDetail.page.jsx
Labels: ✨ Enhancement, hotfix

#107 쿠버네티스 설정 변경
  k8s/ingress.yaml
  k8s/service.yaml
Labels: hotfix

#98 셀럽 상세 페이지 css 보충
  src/src/components/celebrity-detail/CelebProfile.jsx
  src/src/components/celebrity-detail/CelebTextInfo.jsx
  src/src/pages/CelebrityDetail.page.jsx
Labels: ✨ Enhancement

#109 셀럽목록조회 mock api 작업
  src/src/api/celebrityAPI.js
  src/src/api/dto/celebrity.dto.js
  src/src/components/celebrity-list/InfiniteCelebInfo.jsx
  src/src/components/celebrity-list/InfiniteCelebInfo.loader.jsx
  src/src/components/celebrity/CelebInfoGridCardSkeleton.jsx
  src/src/constants/API.js
  src/src/hooks/api/celebrity/useInfiniteCelebInfoQuery.js
  src/src/mocks/handler/celebrityHandlers.js
  src/src/mocks/handler/index.js
  src/src/pages/CelebrityList.page.jsx
  src/src/pages/Test.jsx
Labels: ✨ Enhancement

#112 펀딩 후원하기 페이지 UI, 포트원 연동, 펀딩 정보 조회 api
  src/index.html
  src/package.json
  src/src/assets/icon/kakaopay_icon.png
  src/src/components/common/button/CheckBox.jsx
  src/src/components/fund-detail/information/Information.jsx
  src/src/components/fund-detail/information/MoneyDate.jsx
  src/src/components/fund-detail/information/MoneyDate.skeleton.jsx
  src/src/components/fund-support/FundSupportInfo.jsx
  src/src/components/fund-support/FundSupportInfo.skeleton.jsx
  src/src/components/fund-support/PaymentButton.jsx
  src/src/components/fund/MoneyBarGraph.jsx
  src/src/components/fund/MoneyBarGraph.skeleton.jsx
  src/src/constants/routes.js
  src/src/pages/FundSupport.page.jsx
  src/src/pages/MobilePayment.page.jsx
  src/src/router.jsx
  src/src/styles/GlobalStyle.js
  src/yarn.lock
Labels: ✨ Enhancement

#110 로그인 여부 및 관리자 여부에 따른 접근제한
  src/src/components/common/template/PrivateLayout.jsx
  src/src/constants/routes.js
  src/src/hooks/useDeleteUserInfoInLocalStorage.js
  src/src/pages/Admin.page.jsx
  src/src/pages/MyAccount.page.jsx
  src/src/router.jsx
Labels: ✨ Enhancement

#116 fix: 충돌 이후 router 수정
  src/src/components/celebrity/CelebInfoGridCardSkeleton.jsx
  src/src/constants/routes.js
  src/src/router.jsx
Labels: hotfix

#122 셀럽상세페이지 - 셀럽상세정보(상단), 셀럽관련펀딩목록(하단) mock api 작업
  src/src/api/celebrityAPI.js
  src/src/api/dto/celebrity.dto.js
  src/src/api/fundAPI.js
  src/src/components/celebrity-detail/CelebDetailInfo.jsx
  src/src/components/celebrity-detail/CelebDetailInfoSkeleton.jsx
  src/src/components/celebrity-detail/InfiniteCelebRelatedFund.jsx
  src/src/components/celebrity-detail/skeleton/CelebProfileSkeleton.jsx
  src/src/components/celebrity-detail/skeleton/CelebRankSkeleton.jsx
  src/src/components/celebrity-detail/skeleton/CelebTextInfoSkeleton.jsx
  src/src/hooks/api/celebrity/useCelebDetailInfoQuery.js
  src/src/hooks/api/celebrity/useInfiniteCelebRealtedFundQuery.js
  src/src/mocks/handler/celebrityHandlers.js
  src/src/pages/CelebrityDetail.page.jsx
  src/src/router.jsx
Labels: ✨ Enhancement

#118 펀딩 상세 페이지 출금 UI, mock api
  src/src/api/fundAPI.js
  src/src/components/common/button/ImagePreviewButton.jsx
  src/src/components/fund-detail/DynamicDetailRender.jsx
  src/src/components/fund-detail/comment/Comment.jsx
  src/src/components/fund-detail/comment/index.jsx
  src/src/components/fund-detail/information/Information.jsx
  src/src/components/fund-detail/update/Update.jsx
  src/src/components/fund-detail/update/index.jsx
  src/src/components/fund-detail/withdraw/EvidenceIcon.jsx
  src/src/components/fund-detail/withdraw/EvidenceModal.jsx
  src/src/components/fund-detail/withdraw/InfiniteWithdrawInfo.jsx
  src/src/components/fund-detail/withdraw/InfiniteWithdrawInfo.loader.jsx
  src/src/components/fund-detail/withdraw/Withdraw.jsx
  src/src/components/fund-detail/withdraw/WithdrawInfoBar.jsx
  src/src/components/fund-detail/withdraw/WithdrawInfoBar.skeleton.jsx
  src/src/components/fund-detail/withdraw/index.jsx
  src/src/constants/API.js
  src/src/constants/routes.js
  src/src/hooks/api/fund/useFundWithdrawEvidenceImageMutation.js
  src/src/hooks/api/fund/useInfiniteWithdrawInfoQuery.js
  src/src/main.jsx
  src/src/mocks/handler/fundHandlers.js
  src/src/pages/FundDetail.page.jsx
  src/src/router.jsx
  src/src/utils/EpochConverter.js
  src/yarn.lock
Labels: ✨ Enhancement

#124 출금 신청 페이지 UI 및 mock api
  src/package.json
  src/src/api/fundAPI.js
  src/src/components/fund-detail/withdraw/Withdraw.jsx
  src/src/components/withdraw/FundInfo.jsx
  src/src/components/withdraw/FundInfo.skeleton.jsx
  src/src/components/withdraw/WithdrawForm.jsx
  src/src/constants/API.js
  src/src/hooks/api/fund/useDeleteFundLikeMutation.js
  src/src/hooks/api/fund/useFundBalanceQuery.js
  src/src/hooks/api/fund/useFundWithdrawMutation.js
  src/src/main.jsx
  src/src/mocks/handler/fundHandlers.js
  src/src/pages/Withdraw.page.jsx
  src/src/router.jsx
  src/yarn.lock
Labels: ✨ Enhancement

#128 My펀딩페이지 구현완료
  src/src/api/dto/celebrity.dto.js
  src/src/api/dto/fund.dto.js
  src/src/api/dto/myFund.dto.js
  src/src/api/myFundAPI.js
  src/src/components/fund/FundInfoGridCard.jsx
  src/src/components/my-fund/DynamicRender.jsx
  src/src/components/my-fund/following/MyFollowingList.jsx
  src/src/components/my-fund/host/InfiniteHostFund.jsx
  src/src/components/my-fund/host/MyHostingFundList.jsx
  src/src/components/my-fund/like/MyHeartList.jsx
  src/src/components/my-fund/support/FundingAmoutBadge.jsx
  src/src/components/my-fund/support/InfiniteSupportFund.jsx
  src/src/components/my-fund/support/MyFundingList.jsx
  src/src/constants/API.js
  src/src/constants/TABS.js
  src/src/hooks/api/my-fund/useFollowingCelebQuery.js
  src/src/hooks/api/my-fund/useInfiniteHostFundQuery.js
  src/src/hooks/api/my-fund/useInfiniteSupportFundQuery.js
  src/src/hooks/api/my-fund/useMyFundUserInfoQuery.js
  src/src/mocks/handler/index.js
  src/src/mocks/handler/myFundHandlers.js
  src/src/pages/MyFund.page.jsx
  src/src/router.jsx
Labels: ✨ Enhancement

#130 1차 배포 및 서버 연결
  Dockerfile
  src/package.json
  src/src/api/authAPI.js
  src/src/api/celebrityAPI.js
  src/src/api/dto/fund.dto.js
  src/src/api/fundAPI.js
  src/src/api/instance.js
  src/src/api/userAPI.js
  src/src/components/celebrity-list/InfiniteCelebInfo.jsx
  src/src/components/celebrity-list/InfiniteCelebInfo.loader.jsx
  src/src/components/common/TextEditor.jsx
  src/src/components/common/nav-bar/moblie/MobileSideBar.jsx
  src/src/components/common/nav-bar/pc/PCUserBtn.jsx
  src/src/components/common/template/Layout.jsx
  src/src/components/common/template/PrivateLayout.jsx
  src/src/components/fund-detail/DynamicDetailRender.jsx
  src/src/components/fund-detail/introduction/IntroTextView.jsx
  src/src/components/fund-detail/introduction/Introduction.jsx
  src/src/components/fund-detail/update/Update.jsx
  src/src/components/fund-detail/update/UpdateWrapper.jsx
  src/src/components/fund-detail/withdraw/InfiniteWithdrawInfo.jsx
  src/src/components/fund-detail/withdraw/InfiniteWithdrawInfo.loader.jsx
  src/src/components/fund-detail/withdraw/Withdraw.jsx
  src/src/components/fund-detail/withdraw/WithdrawInfoBar.jsx
  src/src/components/fund-list/InfiniteFundInfo.jsx
  src/src/components/fund-list/InfiniteFundInfo.loader.jsx
  src/src/components/fund/FundInfoGridCard.jsx
  src/src/components/fund/FundMoneyCountdown.jsx
  src/src/components/my-account/UserSettingForm.jsx
  src/src/constants/API.js
  src/src/constants/FORM_INFO.js
  src/src/constants/SORT_ORDER.js
  src/src/hooks/api/auth/useSignUpMutation.js
  src/src/hooks/api/celebrity/useInfiniteCelebInfoQuery.js
  src/src/hooks/api/celebrity/usePostCelebFollowMutation.js
  src/src/hooks/api/celebrity/usePostCelebUnfollowMutation.js
  src/src/hooks/api/fund/useCoAdminQuery.js
  src/src/hooks/api/fund/useDeleteFundLikeMutation.js
  src/src/hooks/api/fund/useFundIntroQuery.js
  src/src/hooks/api/fund/useInfiniteFundInfoQuery.js
  src/src/hooks/api/fund/useInfiniteWithdrawInfoQuery.js
  src/src/hooks/api/fund/usePostFundLikeMutation.js
  src/src/hooks/api/user/useChangeUserSettingMutation.js
  src/src/pages/Error.page.jsx
  src/src/pages/FundList.page.jsx
  src/src/pages/SignUp.page.jsx
  src/src/router.jsx
  src/yarn.lock
Labels: ✨ Enhancement

#131 import문 충돌 해결
  src/src/api/celebrityAPI.js
  src/src/components/common/SearchBar.jsx
  src/src/components/fund-detail/DynamicDetailRender.jsx
  src/src/components/fund-detail/comment/Comment.jsx
  src/src/components/fund-detail/comment/CommentContainer.jsx
  src/src/components/fund-detail/comment/CommentInput.jsx
  src/src/utils/handleEnterKeyDown.js
Labels: hotfix

#132 fix: mock api index.js 경로 수정
  src/src/mocks/handler/index.js
Labels: hotfix

#133 댓글 UI 끝냄 + 나머지 API 연결 작업 중..
  Dockerfile
  src/src/api/authAPI.js
  src/src/api/celebrityAPI.js
  src/src/api/dto/celebrity.dto.js
  src/src/api/fundAPI.js
  src/src/api/instance.js
  src/src/components/celebrity-list/SimpleCelebList.jsx
  src/src/components/common/nav-bar/pc/PCUserBtn.jsx
  src/src/components/fund-detail/DynamicDetailRender.jsx
  src/src/components/fund-detail/comment/Comment.jsx
  src/src/components/fund-detail/comment/CommentInput.jsx
  src/src/components/fund-detail/comment/CommentWrapper.jsx
  src/src/components/fund-detail/comment/InfiniteComment.jsx
  src/src/components/fund-detail/comment/InfiniteReply.jsx
  src/src/components/fund-detail/comment/ReplyInput.jsx
  src/src/components/fund-list/InfiniteFundInfo.jsx
  src/src/constants/API.js
  src/src/hooks/api/auth/useLogInMutation.js
  src/src/hooks/api/fund/useInfiniteComments.js
  src/src/hooks/api/fund/useInfiniteReplyQuery.js
  src/src/hooks/api/fund/usePostCommentMutation.js
  src/src/hooks/api/fund/usePostReplyMutation.js
  src/src/pages/Login.page.jsx
  src/src/pages/SignUp.page.jsx
Labels: ✨ Enhancement

#136 My펀딩 출금승인 UI, Mock API 작업완료
  src/src/api/dto/myFund.dto.js
  src/src/api/myFundAPI.js
  src/src/components/my-fund/DynamicRender.jsx
  src/src/components/my-fund/approve-withdrawal/InfiniteWithdrawalFundInfo.jsx
  src/src/components/my-fund/approve-withdrawal/InfiniteWithdrawalFundInfo.loader.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalApproval.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalFundCard.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalFundInfoSkeleton.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalModal.jsx
  src/src/constants/API.js
  src/src/constants/TABS.js
  src/src/hooks/api/my-fund/useInfiniteWithdrawalFundQuery.js
  src/src/hooks/api/my-fund/usePostWithdrawalApprovalMutation.js
  src/src/hooks/api/my-fund/usePostWithdrawalRejectionMutation.js
  src/src/mocks/handler/myFundHandlers.js
Labels: ✨ Enhancement

#139 결제 확인용 PR
  src/src/api/fundAPI.js
  src/src/api/myFundAPI.js
  src/src/components/celebrity/CelebRequestModal.jsx
  src/src/components/fund-detail/update/Update.jsx
  src/src/components/fund-detail/update/UpdateWrapper.jsx
  src/src/components/fund-support/PaymentButton.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalFundInfoSkeleton.jsx
  src/src/components/my-fund/like/InfiniteHeartFundInfo.jsx
  src/src/components/my-fund/like/MyHeartList.jsx
  src/src/constants/API.js
  src/src/hooks/api/fund/usePostFundUpdateMutation.js
  src/src/hooks/api/my-fund/useInfiniteHeartFundQuery.js
  src/src/pages/Admin.page.jsx
  src/src/pages/FundTextEdit.page.jsx
  src/src/pages/MobilePayment.page.jsx
  src/src/router.jsx
Labels: ✨ Enhancement

#142 회원정보 수정, 셀럽 신청 배포 확인용
  src/src/api/celebrityAPI.js
  src/src/components/my-account/UserSettingForm.jsx
Labels: ✨ Enhancement

#156 fix: loader 에러 해결
  src/src/components/celebrity-list/InfiniteCelebInfo.jsx
  src/src/components/fund-list/InfiniteFundInfo.jsx
  src/src/components/fund-list/InfiniteFundInfo.loader.jsx
  src/src/hooks/api/fund/useInfiniteFundInfoQuery.js
Labels: hotfix

#157 Feat#155
  src/index.html
  src/public/logo.png
  src/public/vite.svg
  src/src/api/fundAPI.js
  src/src/components/celebrity-list/InfiniteCelebInfo.jsx
  src/src/components/fund-list/InfiniteFundInfo.jsx
  src/src/hooks/api/celebrity/useInfiniteCelebInfoQuery.js
  src/src/hooks/api/fund/useInfiniteComments.js
  src/src/hooks/api/fund/useInfiniteFundInfoQuery.js
  src/src/hooks/api/fund/useInfiniteReplyQuery.js
  src/src/hooks/api/fund/useInfiniteUpdate.jsx
  src/src/hooks/api/my-fund/useInfiniteHeartFundQuery.js
  src/src/hooks/useErrorNavigate.js
  src/src/pages/CelebrityList.page.jsx
  src/src/pages/FundList.page.jsx
  src/src/pages/FundSupport.page.jsx
  src/src/pages/FundTextEdit.page.jsx
  src/src/pages/Login.page.jsx
  src/src/pages/Test.jsx
  src/src/router.jsx
Labels: hotfix

#158 셀럽 상세 팔로잉 기능
  src/src/api/celebrityAPI.js
  src/src/hooks/api/celebrity/usePostCelebFollowMutation.js
  src/src/hooks/api/celebrity/usePostCelebUnfollowMutation.js
Labels: hotfix

#159 feat: My 펀딩 api 연결
  src/src/api/fundAPI.js
  src/src/api/myFundAPI.js
  src/src/components/my-fund/approve-withdrawal/InfiniteWithdrawalFundInfo.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalFundCard.jsx
  src/src/components/my-fund/approve-withdrawal/WithdrawalModal.jsx
  src/src/components/my-fund/host/InfiniteHostFund.jsx
  src/src/components/my-fund/support/InfiniteSupportFund.jsx
  src/src/components/withdraw/WithdrawForm.jsx
  src/src/hooks/api/my-fund/usePostWithdrawalApprovalMutation.js
  src/src/hooks/api/my-fund/usePostWithdrawalRejectionMutation.js
  src/src/hooks/api/my-fund/useWithdrawalFundQuery.js
Labels: ✨ Enhancement

#160 feat: 펀딩 상세 페이지 남은 금액이 없을 때 0으로 나타내는 기능 추가
  src/src/components/fund-detail/information/Information.jsx
Labels: ✨ Enhancement

#161 feat: 마이 펀딩 출금 승인 에러 바운더리 추가
  src/src/api/myFundAPI.js
  src/src/components/my-fund/approve-withdrawal/WithdrawalApproval.jsx
  src/src/constants/FORM_INFO.js
  src/src/hooks/api/my-fund/useWithdrawalFundQuery.js
Labels: ✨ Enhancement

#162 feat: 마이 펀딩 출금 승인, 거절 api data => params로 변경
  src/src/api/myFundAPI.js
  src/src/hooks/api/my-fund/usePostWithdrawalApprovalMutation.js
  src/src/hooks/api/my-fund/usePostWithdrawalRejectionMutation.js
Labels: hotfix

#163 feat: 펀딩 출금 내역의 dto 변경
  src/src/api/dto/fund.dto.js
Labels: ✨ Enhancement
